name: Pull Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写 docker 镜像的名称（和版本号），多个用英文逗号分开'
        required: true
        default: 'harness/gitness:latest'
      platform:
        description: '请填写 docker 镜像平台类型'
        required: true
        default: 'linux/amd64'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        platform="${{ github.event.inputs.platform }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "$platform"
          tar_file="${image//[\/:]/-}-${platform//[\/:]/-}.tar"
          docker save "${image}" -o "$tar_file"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images
        path: '*.tar'
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *.tar
