name: Pull Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写 docker 镜像的名称（和版本号），多个用英文逗号分开'
        required: true
        default: 'harness/gitness:latest'
      platform:
        description: '请填写 docker 镜像平台类型'
        required: true
        default: 'linux/amd64'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      id: package_image
      run: |
        images="${{ github.event.inputs.docker_images }}"
        platform="${{ github.event.inputs.platform }}"
        
        IFS=',' read -r -a image_array <<< "$images"
        
        for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "$platform"
        done
        
        output_file="docker-images-${platform//[\/:]/-}-$(date +%Y%m%d_%H%M%S).tar.gz"
        docker save "${image_array[@]}" | gzip > "$output_file"

        echo "output_file=$output_file" >> $GITHUB_OUTPUT
        echo "所有镜像已保存到: $output_file"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.package_image.outputs.output_file }}
        path: ${{ steps.package_image.outputs.output_file }}
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *.tar.gz
